import service from '@/utils/request'

export const createDocument = (data: any) => service({ url: '/api/v1/document', method: 'post', data })
export const updateDocument = (data: any) => service({ url: '/api/v1/document', method: 'put', data })
export const setDocumentRecommend = (data: any) => service({ url: '/api/v1/document/recommend', method: 'put', data })
export const setDocumentReconvert = (data?: any) => service({ url: '/api/v1/document/reconvert', method: 'put', data })
export const deleteDocument = (params: any) => service({ url: '/api/v1/document', method: 'delete', params })
export const getDocument = (params: any) => service({ url: '/api/v1/document', method: 'get', params })
export const getRelatedDocuments = (params: any) => service({ url: '/api/v1/document/related', method: 'get', params })
export const listDocumentForHome = (params: any) => service({ url: '/api/v1/document/home', method: 'get', params })
export const listDocument = (params: any) => service({ url: '/api/v1/document/list', method: 'get', params })
export const searchDocument = (params: any) => service({ url: '/api/v1/document/search', method: 'get', params })
export const downloadDocument = (params: any) => service({ url: '/api/v1/document/download', method: 'get', params })
export const listRecycleDocument = (params: any) => service({ url: '/api/v1/document/recycle', method: 'get', params })
export const recoverRecycleDocument = (data: any) => service({ url: '/api/v1/document/recycle', method: 'put', data })
export const deleteRecycleDocument = (params: any) => service({ url: '/api/v1/document/recycle', method: 'delete', params })
export const clearRecycleDocument = (params: any) => service({ url: '/api/v1/document/recycle/all', method: 'delete', params })
export const getDocumentScore = (params: any) => service({ url: '/api/v1/document/score', method: 'get', params })
export const setDocumentScore = (data: any) => service({ url: '/api/v1/document/score', method: 'post', data })
export const setDocumentsCategory = (data: any) => service({ url: '/api/v1/document/category', method: 'put', data })
export const checkDocument = (data: any) => service({ url: '/api/v1/document/check', method: 'put', data })
export const downloadDocumentToBeReviewed = (params: any) => service({ url: '/api/v1/document/download/bereviewed', method: 'get', params })
export const setDocumentsLanguage = (data: any) => service({ url: '/api/v1/document/language', method: 'put', data })