import service from '@/utils/request'

export const logout = (params?: any) => service({ url: '/api/v1/user/logout', method: 'delete', params })
export const getUser = (params?: any) => service({ url: '/api/v1/user', method: 'get', params })
export const canIUploadDocument = () => service({ url: '/api/v1/user/caniuploaddocument', method: 'get' })
export const canIPublishArticle = () => service({ url: '/api/v1/user/canipublisharticle', method: 'get' })
export const updateUserProfile = (data: any) => service({ url: '/api/v1/user/profile', method: 'put', data })
export const deleteUser = (params: any) => service({ url: '/api/v1/user', method: 'delete', params })
export const addUser = (data: any) => service({ url: '/api/v1/user', method: 'post', data })
export const setUser = (data: any) => service({ url: '/api/v1/user', method: 'put', data })
export const listUser = (params: any) => service({ url: '/api/v1/user/list', method: 'get', params })
export const getUserCaptcha = (params: any) => service({ url: '/api/v1/user/captcha', method: 'get', params })
export const getDynamics = (params: any) => service({ url: '/api/v1/user/dynamic', method: 'get', params })
export const getUserDownloads = (params: any) => service({ url: '/api/v1/user/download', method: 'get', params })
export const getUserPermissions = (params?: any) => service({ url: '/api/v1/user/permission', method: 'get', params })
export const getSignedToday = () => service({ url: '/api/v1/user/sign', method: 'get' })
export const signToday = () => service({ url: '/api/v1/user/sign', method: 'put' })
export const listUserGroup = (params?: any) => service({ url: '/api/v1/user/group', method: 'get', params })